### ISSUE TITLE
[Feature] 백엔드 서버 주소를 .env에서 관리하도록 수정

### ISSUE THREAD

**Issue by SeonjaeHyeon** [UXMUnderGraduate/22-S-Front#69]
**Description**
---
- 팀원마다 서버 실행환경이 달라 커밋할 때마다 서버 주소가 바뀌어 불편함.  
- 백엔드 서버 주소를 .env에서 관리할 수 있도록 수정하는 것이 필요함.  
---

**TODO**
- [ ] todo
- [ ] todo

---

**ETC**
기타사항

**Comment by MinsuKim21** [comment]
이거 씹인정
